npm install list.js@latest
	bundle update
	git status --short

install: install-js setup-js install-gems

fmt:
	bundle exec rufo _plugins

s serve: fmt
	source .env \
		&& bundle exec jekyll serve --trace --livereload


build-dev:
	DEBUG=1 source .env \
		&& bundle exec jekyll build --trace

build-prod:
	JEKYLL_ENV=production bundle exec jekyll build --trace
